// Constants of the account pages (workstream S). Never inline these numbers.

export const ORDERS_PAGE_SIZE = 10;
export const DASHBOARD_RECENT_ORDERS = 3;
/** A dashboard panel that has not answered after this long reports "unavailable" instead of blocking the page. */
export const PANEL_TIMEOUT_MS = 4000;
/** The dashboard derives the contract from the customer's newest orders (the platform page limit is 500). */
export const DASHBOARD_ORDERS_LIMIT = 100;
export const RECURRING_SUMMARY_LIMIT = 100;

export type OrderStatusFilter = 'all' | 'open' | 'completed' | 'cancelled';
export const ORDER_STATUS_FILTER_KEYS: readonly OrderStatusFilter[] = ['all', 'open', 'completed', 'cancelled'];

/** Query predicate of each filter (`null` = no extra condition). */
export const ORDER_STATUS_PREDICATE: Record<OrderStatusFilter, string | null> = {
  all: null,
  open: 'orderState in ("Open","Confirmed")',
  completed: 'orderState = "Complete"',
  cancelled: 'orderState = "Cancelled"',
};

/** Orders generated by a Recurring Order are monthly bills, not orders the customer placed. */
export const NOT_RECURRING_GENERATED = 'recurringOrder is not defined';

/** Line items of these states are what "the customer holds" (D-021); recurring orders in these states no longer bill. */
export const ENDED_RECURRING_STATES: readonly string[] = ['Expired', 'Canceled'];
