import type { RecurringOrder } from '@commercetools/platform-sdk';
import type { RecurringOrderSummary } from '../types';
import { getLocalizedString } from '../utils';
import { mapLine } from './cart';

/** Lifecycle to the shopper-facing state. Expired and Failed are `Other` (neutral tag; the raw value stays in `stateRaw`). */
export function mapRecurringState(state: string): RecurringOrderSummary['state'] {
  return state === 'Active' || state === 'Paused' || state === 'Canceled' ? state : 'Other';
}

/**
 * Pure mapping from an SDK Recurring Order to the summary. The items live in the recurring cart, so `cart` must be expanded
 * (with `lineItems[*].recurrenceInfo.recurrencePolicy` for the cadence name) and `originOrder` too, for the date of the
 * first order (`lastOrderAt` is only set for orders generated by the schedule).
 */
export function mapRecurringOrder(ro: RecurringOrder, ctx: { locale: string }): RecurringOrderSummary {
  const cartLines = ro.cart.obj?.lineItems ?? [];
  const policy = cartLines.find((l) => l.recurrenceInfo)?.recurrenceInfo?.recurrencePolicy.obj;
  const schedule = ro.schedule;
  const fallback =
    schedule.type === 'standard' ? `${schedule.value} ${schedule.intervalUnit}` : schedule.type === 'dayOfMonth' ? `Day ${schedule.day}` : '';
  const lastOrderAt = ro.lastOrderAt ?? ro.originOrder.obj?.createdAt;
  return {
    id: ro.id,
    state: mapRecurringState(ro.recurringOrderState),
    stateRaw: ro.recurringOrderState,
    cadenceLabel: (policy ? getLocalizedString(policy.name, ctx.locale) || policy.key : '') || fallback,
    ...(policy?.key ? { policyKey: policy.key } : {}),
    lines: cartLines.map((l) => {
      const line = mapLine(l, ctx.locale);
      return { id: line.id, sku: line.sku, name: line.name, quantity: line.quantity, ...(line.image ? { image: line.image } : {}) };
    }),
    ...(ro.nextOrderAt ? { nextOrderAt: ro.nextOrderAt } : {}),
    ...(lastOrderAt ? { lastOrderAt } : {}),
  };
}
