function Account({sub,id}){const{user,setUser,bookings,orders}=useApp();
const T=[['','Overview'],['labs','Lab tests'],['appointments','Appointments'],['orders','Orders']];
const ready=LABS.filter(l=>l.status==='ready').length;
let body;
if(sub==='labs'&&id)body=<LabDetail id={id}/>;
else if(sub==='labs')body=<div className="card" style={{padding:0}}><div style={{padding:'20px 20px 8px'}}><h2>Lab tests</h2><p className="meta">Select a test to see the full results.</p></div>{LABS.map(l=><div key={l.id} className="lrow" onClick={()=>go('/account/labs/'+l.id)}><div><b style={{color:'var(--color-navy-900)'}}>{l.name}</b><div className="meta">{fmtDate(l.date)} · {l.lab}</div></div><span className={'badge '+(l.status==='ready'?'b-ok':'b-wait')}>{l.status==='ready'?'Results ready':'Processing'}</span><span>→</span></div>)}</div>;
else if(sub==='appointments')body=<div className="stack"><h2>Appointments</h2>{bookings.length?bookings.map(b=>{const d=DOCTORS.find(x=>x.id===b.docId);return <div key={b.id} className="card row sp"><div><b style={{color:'var(--color-navy-900)'}}>{d.name}</b><div className="meta">{fmtDate(b.date)} at {b.time} · {b.mode==='remote'?'Video session':d.clinic}</div></div><span className="badge b-info">{b.id}</span></div>}):<div className="card muted">No appointments yet. <a href="#/doctors/remote">Book one</a></div>}</div>;
else if(sub==='orders')body=<div className="stack"><h2>Orders</h2>{orders.length?orders.map(o=><div key={o.id} className="card row sp"><div><b style={{color:'var(--color-navy-900)'}}>{o.id}</b><div className="meta">{o.items.map(i=>i.name).join(', ')}</div></div><div className="row"><b>{money(o.total)}</b><a className="btn o sm" href={'#/order/'+o.id}>Track</a></div></div>):<div className="card muted">No orders yet. <a href="#/prescriptions">Order from a prescription</a></div>}</div>;
else body=<div className="stack" style={{gap:24}}><div><h1 style={{fontSize:28}}>Hello, {user.name.split(' ')[0]}</h1><p className="meta">{user.email}</p></div><div className="stat"><a className="card" onClick={()=>go('/account/labs')}><b>{ready}</b>Lab results ready</a><a className="card" onClick={()=>go('/account/appointments')}><b>{bookings.length}</b>Appointments</a><a className="card" onClick={()=>go('/account/orders')}><b>{orders.length}</b>Orders</a></div>
<div className="card" style={{padding:0}}><div style={{padding:'20px 20px 8px'}}><h2>Latest lab results</h2></div>{LABS.slice(0,3).map(l=><div key={l.id} className="lrow" onClick={()=>go('/account/labs/'+l.id)}><div><b style={{color:'var(--color-navy-900)'}}>{l.name}</b><div className="meta">{fmtDate(l.date)}</div></div><span className={'badge '+(l.status==='ready'?'b-ok':'b-wait')}>{l.status==='ready'?'Results ready':'Processing'}</span><span>→</span></div>)}</div></div>;
return <main><div className="w"><div className="side"><div className="stack"><nav>{T.map(([k,t])=><a key={k} className={(sub||'')===k?'on':''} href={'#/account'+(k?'/'+k:'')}>{t}</a>)}</nav><a className="btn o sm" onClick={()=>{setUser(null);go('/login')}}>Sign out</a></div><div>{body}</div></div></div></main>}
function LabDetail({id}){const l=LABS.find(x=>x.id===id);if(!l)return <p>Not found.</p>;
return <div className="stack" style={{gap:20}}><a href="#/account/labs">← All lab tests</a>
<div className="card stack"><div className="row sp"><h1 style={{fontSize:26}}>{l.name}</h1><span className={'badge '+(l.status==='ready'?'b-ok':'b-wait')}>{l.status==='ready'?'Results ready':'Processing'}</span></div>
<dl className="kv"><dt>Collected</dt><dd>{fmtDate(l.date)}</dd><dt>Ordered by</dt><dd>{l.by}</dd><dt>Laboratory</dt><dd>{l.lab}</dd></dl><div className="note">{l.note}</div></div>
{l.res.length>0&&<div className="card" style={{padding:8}}><table className="t"><thead><tr><th>Test</th><th>Result</th><th>Reference range</th><th></th></tr></thead><tbody>{l.res.map(([n,v,u,lo,hi])=>{const f=flag(v,lo,hi);const span=(hi-lo)||1;const pos=Math.max(4,Math.min(96,((v-lo)/span)*100));return <tr key={n}><td><b style={{color:'var(--color-navy-900)',fontWeight:500}}>{n}</b></td><td><b>{v}</b> <span className="muted">{u}</span></td><td><div className="rng" style={f==='ok'?{}:{background:'var(--color-danger-50)'}} ><i style={{left:pos+'%'}} className=""></i></div><div className="meta" style={{fontSize:12,marginTop:6}}>{lo===0?'< '+hi:lo+' – '+hi} {u}</div></td><td><span className={'badge '+(f==='ok'?'b-ok':'b-no')}>{f==='ok'?'Normal':f==='hi'?'High':'Low'}</span></td></tr>})}</tbody></table></div>}
{l.res.length>0&&<div className="row"><button className="btn o sm">Download PDF</button><a className="btn sm" href="#/doctors/remote">Discuss with a doctor</a></div>}</div>}
Object.assign(window,{Account});
