function Prescriptions(){const{cart,addToCart}=useApp();const[q,setQ]=useState('');const[rx,setRx]=useState(null);const[err,setErr]=useState('');const[sel,setSel]=useState({});const[toast,setToast]=useState(false);
const find=(v)=>{const k=(v||q).trim().toUpperCase().replace(/^RX\s?-?/,'RX-');const r=RX[k];if(r){setRx({no:k,...r});setErr('');setSel(Object.fromEntries(r.meds.map(m=>[m.id,true])))}else{setRx(null);setErr('We couldn’t find “'+(v||q)+'”. Check the number printed on your prescription.')}};
const chosen=rx?rx.meds.filter(m=>sel[m.id]):[];const total=chosen.reduce((s,m)=>s+m.price,0);
const add=()=>{addToCart(chosen.map(m=>({key:rx.no+m.id,rx:rx.no,name:m.name,qty:m.qty,price:m.price})));setToast(true);setTimeout(()=>setToast(false),5000)};
return <><Head title="Prescriptions" sub="Enter the RX number from your doctor to review your medications and order delivery.">
<form className="row" style={{marginTop:20,flexWrap:'nowrap',maxWidth:560}} onSubmit={e=>{e.preventDefault();find()}}><input className="inp" style={{background:'#fff'}} placeholder="e.g. RX-48213" value={q} onChange={e=>setQ(e.target.value)}/><button className="btn">Search</button></form>
<div className="row" style={{marginTop:12,fontSize:13}}><span className="muted">Try:</span>{Object.keys(RX).map(k=><a key={k} className="badge b-info" onClick={()=>{setQ(k);find(k)}}>{k}</a>)}</div></Head>
<main><div className="w" style={{maxWidth:860,marginTop:32}}>
{err&&<div className="card" style={{color:'#b3402a'}}>{err}</div>}
{!rx&&!err&&<div className="card muted">Your medications will appear here after you search.</div>}
{rx&&<div className="card"><div className="row sp" style={{paddingBottom:16,borderBottom:'1px solid var(--color-border)'}}><div><h2>{rx.no}</h2><div className="meta">Prescribed by {rx.doctor} · {fmtDate(rx.date)}</div></div><div className="row"><span className="badge b-n">Patient: {rx.patient}</span><span className="badge b-ok">{rx.refills} refills left</span></div></div>
<label className="chk" style={{padding:'16px 0 0'}}><input type="checkbox" checked={chosen.length===rx.meds.length} onChange={e=>setSel(Object.fromEntries(rx.meds.map(m=>[m.id,e.target.checked])))}/>Select all medications</label>
{rx.meds.map(m=><div className="med" key={m.id}><input type="checkbox" style={{width:20,height:20,accentColor:'var(--color-brand-500)'}} checked={!!sel[m.id]} onChange={e=>setSel({...sel,[m.id]:e.target.checked})}/><div><b>{m.name}</b><div className="meta">{m.sig}</div></div><span className="meta">Qty {m.qty}</span><b>{money(m.price)}</b></div>)}
<div className="row sp" style={{paddingTop:16,borderTop:'1px solid var(--color-border)'}}><div><span className="muted">{chosen.length} selected · </span><b style={{fontSize:20,color:'var(--color-navy-700)'}}>{money(total)}</b></div><button className="btn" disabled={!chosen.length} onClick={add}>Add to cart</button></div></div>}</div>
{toast&&<div className="toast">Added to cart<a href="#/cart">View cart →</a></div>}</main></>}
function Cart(){const{cart,setCart}=useApp();const sub=cart.reduce((s,i)=>s+i.price,0);
return <><Head title="Your cart"/><main><div className="w"><div className="two" style={{marginTop:32}}><div className="card">{cart.length?cart.map(i=><div className="med" style={{gridTemplateColumns:'1fr auto auto auto'}} key={i.key}><div><b>{i.name}</b><div className="meta">{i.rx} · Qty {i.qty}</div></div><span/><b>{money(i.price)}</b><a onClick={()=>setCart(cart.filter(x=>x.key!==i.key))}>Remove</a></div>):<div className="stack"><p className="muted">Your cart is empty.</p><a className="btn" style={{justifySelf:'start'}} href="#/prescriptions">Find a prescription</a></div>}</div>
{cart.length>0&&<aside className="card stack"><h2>Summary</h2><div className="row sp"><span>Subtotal</span><b>{money(sub)}</b></div><div className="row sp"><span>Standard delivery</span><b className="badge b-ok">FREE</b></div><div className="row sp" style={{borderTop:'1px solid var(--color-border)',paddingTop:12}}><b>Total</b><b style={{fontSize:20,color:'var(--color-navy-700)'}}>{money(sub)}</b></div><a className="btn full" href="#/checkout">Checkout</a></aside>}</div></div></main></>}
function Checkout(){const{cart,user,addOrder}=useApp();const[ship,setShip]=useState('std');const[f,setF]=useState({name:user.name,addr:'',city:'',zip:'',phone:''});const set=k=>e=>setF({...f,[k]:e.target.value});
if(!cart.length)return <div className="w"><p style={{padding:40}}>Your cart is empty. <a href="#/prescriptions">Find a prescription</a></p></div>;
const sub=cart.reduce((s,i)=>s+i.price,0),fee=ship==='same'?5:0;
const submit=e=>{e.preventDefault();const id='ORD-'+Math.floor(100000+Math.random()*899999);addOrder({id,date:new Date().toISOString().slice(0,10),items:cart,total:sub+fee,ship,addr:`${f.addr}, ${f.city} ${f.zip}`});go('/order/'+id)};
return <><Head title="Checkout"/><main><div className="w"><form className="two" style={{marginTop:32}} onSubmit={submit}><div className="stack" style={{gap:24}}>
<div className="card stack"><h2>Delivery address</h2><label className="fld">Full name<input className="inp" required value={f.name} onChange={set('name')}/></label><label className="fld">Street address<input className="inp" required value={f.addr} onChange={set('addr')} placeholder="123 W 34th St, Apt 5"/></label><div className="f2"><label className="fld">City<input className="inp" required value={f.city} onChange={set('city')}/></label><label className="fld">ZIP<input className="inp" required value={f.zip} onChange={set('zip')}/></label></div><label className="fld">Phone<input className="inp" type="tel" required value={f.phone} onChange={set('phone')}/></label></div>
<div className="card stack"><h2>Delivery speed</h2>{[['std','Standard · 1–2 days','FREE'],['same','Same-day · by 8 pm','$5.00']].map(([k,t,p])=><label key={k} className="chk row sp" style={{border:'1.5px solid '+(ship===k?'var(--color-brand-500)':'var(--color-border)'),borderRadius:8,padding:14}}><span className="row"><input type="radio" name="s" checked={ship===k} onChange={()=>setShip(k)}/>{t}</span><b>{p}</b></label>)}</div>
<div className="card stack"><h2>Payment</h2><label className="fld">Card number<input className="inp" required defaultValue="4242 4242 4242 4242"/></label><div className="f2"><label className="fld">Expiry<input className="inp" required defaultValue="12/28"/></label><label className="fld">CVC<input className="inp" required defaultValue="123"/></label></div></div></div>
<aside className="card sticky stack"><h2>Order summary</h2>{cart.map(i=><div key={i.key} className="row sp" style={{fontSize:14}}><span>{i.name}</span><b>{money(i.price)}</b></div>)}<div className="row sp"><span>Delivery</span><b>{fee?money(fee):'FREE'}</b></div><div className="row sp" style={{borderTop:'1px solid var(--color-border)',paddingTop:12}}><b>Total</b><b style={{fontSize:20,color:'var(--color-navy-700)'}}>{money(sub+fee)}</b></div><button className="btn full">Place order</button></aside></form></div></main></>}
function Order({id}){const{orders}=useApp();const o=orders.find(x=>x.id===id);if(!o)return <div className="w"><p style={{padding:40}}>Order not found.</p></div>;
return <main><div className="w" style={{maxWidth:640}}><div className="card stack" style={{marginTop:48}}><span className="badge b-ok" style={{justifySelf:'start'}}>Order placed</span><h1 style={{fontSize:30}}>Your medication is on its way.</h1><dl className="kv"><dt>Order</dt><dd>{o.id}</dd><dt>Items</dt><dd>{o.items.map(i=>i.name).join(', ')}</dd><dt>Deliver to</dt><dd>{o.addr}</dd><dt>Estimate</dt><dd>{o.ship==='same'?'Today by 8 pm':'1–2 business days'}</dd><dt>Total</dt><dd>{money(o.total)}</dd></dl>
<ul className="tl"><li className="d">Order received</li><li>Pharmacist review</li><li>Packed and shipped</li><li>Delivered</li></ul><div className="row"><a className="btn" href="#/account/orders">My orders</a><a className="btn o" href="#/prescriptions">Search another RX</a></div></div></div></main>}
Object.assign(window,{Prescriptions,Cart,Checkout,Order});
