import { loadProductImages } from './data/images';
import { doctorSteps, foundationSteps, medicationSteps, type ProductOptions } from './steps';
import { getAdminRoot, isMain, makeCtx, parseFlags, runSteps, type Ctx, type RunSummary, type Step } from './lib';

/**
 * Creates or checks everything the storefront needs, in dependency order:
 * channels, tax categories, order states (+ transitions), custom types, product types, categories,
 * shipping zone and methods, doctor products, medication products, inventory.
 *
 *   npx tsx scripts/seed/seed.ts [--dry-run] [--only <product-key>]
 *
 * Idempotent: a second run reports 0 changes. Existing resources are compared, never overwritten;
 * a difference stops the run with exit 1. Images come from data/product-images.json (generated by update-images.ts).
 * Run cleanup-sample.ts first on a project that still holds the sample furniture data.
 */
export function seedSteps(ctx: Ctx, o: ProductOptions = {}): Step[] {
  return [...foundationSteps(ctx), ...doctorSteps(ctx, o), ...medicationSteps(ctx, o)];
}

export async function runSeed(ctx: Ctx, o: ProductOptions = {}): Promise<RunSummary> {
  const summary = await runSteps(seedSteps(ctx, o), ctx.log);
  ctx.log(summary.ok ? `${ctx.dryRun ? 'dry run: ' : ''}${summary.changed} change(s) in ${summary.total} step(s)` : `stopped after ${summary.total} step(s), ${summary.changed} change(s): fix the difference above`);
  return summary;
}

async function main() {
  const flags = parseFlags(process.argv.slice(2));
  const { root } = await getAdminRoot();
  const summary = await runSeed(makeCtx(root, flags), { images: loadProductImages(), only: flags.only });
  if (!summary.ok) process.exit(1);
}

if (isMain(__filename)) main().catch((e) => { console.error(e instanceof Error ? e.message : e); process.exit(1); });
