#!/usr/bin/env node
// Verifies the implementation plan under plan/ and (optionally) regenerates derived sections.
//   node plan/verify-plan.mjs              -> check only (exit 1 on any error)
//   node plan/verify-plan.mjs --sync       -> regenerate graph, STATUS counts, manual-test table, then check
// No dependencies. Run from the repository root.
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';

const ROOT = process.cwd();
const P = (...a) => join(ROOT, 'plan', ...a);
const SYNC = process.argv.includes('--sync');
const CHANGES = ['bootstrap-nextjs-storefront', 'malva-storefront-design', 'grocery-storefront-features'];
const errors = [];
const warns = [];
const err = (m) => errors.push(m);

const read = (f) => readFileSync(f, 'utf8');

// ---------- workstreams ----------
const wsDir = P('workstreams');
const wsFiles = readdirSync(wsDir).filter((f) => /^[A-Z]-.+\.md$/.test(f)).sort();
const ws = {};
for (const f of wsFiles) {
  const id = f[0];
  const text = read(join(wsDir, f));
  const depLine = text.match(/\*\*Depends on:\*\*\s*([^·\n]+)/);
  let deps = [];
  if (!depLine) err(`${f}: missing "**Depends on:**"`);
  else {
    const raw = depLine[1].trim();
    deps = expandDeps(raw);
  }
  const tasks = [...text.matchAll(/^- \[( |x)\] ([A-Z])-(\d{2}) /gm)].map((m) => ({ done: m[1] === 'x', letter: m[2], n: Number(m[3]) }));
  ws[id] = { file: f, text, deps, tasks };
}
function expandDeps(raw) {
  raw = raw.trim();
  if (raw === '—' || raw === '-') return [];
  const out = new Set();
  for (const m of raw.matchAll(/\b([A-Z])\s*–\s*([A-Z])\b/g)) for (let c = m[1].charCodeAt(0); c <= m[2].charCodeAt(0); c++) out.add(String.fromCharCode(c));
  for (const m of raw.replace(/\b[A-Z]\s*–\s*[A-Z]\b/g, '').matchAll(/\b[A-Z]\b/g)) out.add(m[0]);
  return [...out].sort();
}
const expectedLetters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
for (const L of expectedLetters) if (!ws[L]) err(`workstream ${L} missing`);

for (const [L, w] of Object.entries(ws)) {
  for (const d of w.deps) {
    if (!ws[d]) err(`${L}: depends on unknown workstream ${d}`);
    else if (d >= L) err(`${L}: depends on ${d}, which is not an earlier letter`);
  }
  if (w.tasks.length === 0) err(`${L}: no tasks`);
  w.tasks.forEach((t, i) => {
    if (t.letter !== L) err(`${L}: task id ${t.letter}-${String(t.n).padStart(2, '0')} has wrong letter`);
    if (t.n !== i + 1) err(`${L}: task numbering not sequential at ${t.letter}-${String(t.n).padStart(2, '0')}`);
  });
}

// ---------- DEPENDENCY-PLAN table ----------
const depPlanPath = P('DEPENDENCY-PLAN.md');
let depPlan = read(depPlanPath);
const rows = [...depPlan.matchAll(/^\| ([A-Z]) \| ([^|]+)\| ([^|]+)\| ([^|]+)\|/gm)];
const tableDeps = {};
for (const m of rows) {
  tableDeps[m[1]] = expandDeps(m[4]);
}
for (const L of expectedLetters) {
  if (!tableDeps[L]) err(`DEPENDENCY-PLAN: missing row for ${L}`);
  else if (ws[L] && [...tableDeps[L]].sort().join() !== [...ws[L].deps].sort().join()) err(`DEPENDENCY-PLAN: ${L} depends [${tableDeps[L]}] but workstream file says [${ws[L].deps}]`);
}

if (SYNC) {
  // regenerate the 'Unblocks' column (direct dependents)
  depPlan = depPlan.split('\n').map((l) => {
    const m = l.match(/^\| ([A-Z]) \|/);
    if (!m || !ws[m[1]]) return l;
    const c = l.split('|');
    if (c.length < 8) return l;
    const dependents = expectedLetters.filter((x) => ws[x]?.deps.includes(m[1]));
    c[6] = ` ${dependents.length ? dependents.join(', ') : '—'} `;
    return c.join('|');
  }).join('\n');
  const edges = [];
  for (const L of expectedLetters) for (const d of ws[L]?.deps ?? []) edges.push(`  ${d} --> ${L}`);
  const names = expectedLetters.map((L) => `  ${L}["${L} ${(ws[L]?.file ?? '').slice(2, -3).replace(/-/g, ' ')}"]`);
  const graph = ['<!-- GRAPH:BEGIN (generated by plan/verify-plan.mjs --sync) -->', '```mermaid', 'graph LR', ...names, ...edges, '```', '<!-- GRAPH:END -->'].join('\n');
  if (depPlan.includes('<!-- GRAPH:BEGIN')) depPlan = depPlan.replace(/<!-- GRAPH:BEGIN[\s\S]*?<!-- GRAPH:END -->/, graph);
  else err('DEPENDENCY-PLAN: GRAPH markers missing');
  writeFileSync(depPlanPath, depPlan);
}

// ---------- STATUS ----------
const statusPath = P('STATUS.md');
let status = read(statusPath);
for (const L of expectedLetters) {
  const w = ws[L];
  if (!w) continue;
  const total = w.tasks.length;
  const done = w.tasks.filter((t) => t.done).length;
  const re = new RegExp(`^\\| ${L} \\| ([^|]+)\\| (\\d+) \\| (\\d+) \\|`, 'm');
  const m = status.match(re);
  if (!m) { err(`STATUS: missing row for ${L}`); continue; }
  if (SYNC) status = status.replace(re, `| ${L} | ${m[1]}| ${total} | ${done} |`);
  else if (Number(m[2]) !== total || Number(m[3]) !== done) err(`STATUS: ${L} says ${m[2]}/${m[3]} but workstream has ${total} tasks, ${done} done (run --sync)`);
}
if (SYNC) writeFileSync(statusPath, status);

// ---------- DECISIONS / TODO ids ----------
const decisions = read(P('DECISIONS.md'));
const todoPath = P('TODO-MANUAL-TESTING.md');
let todo = read(todoPath);
const have = (text, id) => new RegExp(`\\|\\s*${id}\\s*\\|`).test(text);
const FUTURE = new Set(['D-099']);
const planTexts = { ...Object.fromEntries(Object.entries(ws).map(([k, v]) => [v.file, v.text])) };
for (const f of ['JUNIOR-GUIDE.md', 'DEPENDENCY-PLAN.md', 'README.md']) if (existsSync(P(f))) planTexts[f] = read(P(f));
for (const c of CHANGES) {
  for (const f of ['proposal.md', 'design.md', 'tasks.md']) {
    const p = join(ROOT, 'openspec', 'changes', c, f);
    if (existsSync(p)) planTexts[`${c}/${f}`] = read(p);
  }
}
for (const [file, text] of Object.entries(planTexts)) {
  for (const id of new Set(text.match(/\bD-\d{3}\b/g) ?? [])) if (!FUTURE.has(id) && !have(decisions, id)) err(`${file}: references ${id}, not in DECISIONS.md`);
  for (const id of new Set(text.match(/\b(?:OA|SO)-\d{2}\b/g) ?? [])) if (!have(todo, id)) err(`${file}: references ${id}, not in TODO-MANUAL-TESTING.md`);
}

// ---------- manual tests (sync + check) ----------
const mRe = /^- (M-[A-Z]-\d+)(?:\s*\(([^)]*)\))?:\s*(.+)$/gm;
const manual = [];
for (const [L, w] of Object.entries(ws)) for (const m of w.text.matchAll(mRe)) manual.push({ id: m[1], ws: L, needs: [...new Set(`${m[2] ?? ''} ${m[3]}`.match(/\bOA-\d{2}\b/g) ?? [])], text: m[3].trim() });
const seen = new Set();
for (const m of manual) { if (seen.has(m.id)) err(`manual test ${m.id} defined twice`); seen.add(m.id); }
const BEGIN = '<!-- M-TESTS:BEGIN (generated by plan/verify-plan.mjs --sync; statuses are preserved) -->';
const END = '<!-- M-TESTS:END -->';
if (!todo.includes('<!-- M-TESTS:BEGIN') || !todo.includes(END)) err('TODO: M-TESTS markers missing');
else if (SYNC) {
  const old = Object.fromEntries([...todo.matchAll(/^\| (M-[A-Z]-\d+) \|.*\| ([^|]+) \|$/gm)].map((m) => [m[1], m[2].trim()]));
  const lines = ['| ID | WS | Manual test (what to do → expected) | Needs | Status |', '| --- | --- | --- | --- | --- |'];
  for (const m of manual) lines.push(`| ${m.id} | ${m.ws} | ${m.text.replace(/\|/g, '\\|')} | ${m.needs.join(', ') || '—'} | ${old[m.id] ?? 'TODO'} |`);
  todo = todo.replace(/<!-- M-TESTS:BEGIN[\s\S]*?<!-- M-TESTS:END -->/, `${BEGIN}\n${lines.join('\n')}\n${END}`);
  writeFileSync(todoPath, todo);
} else {
  for (const m of manual) if (!have(todo, m.id)) err(`TODO: manual test ${m.id} not in table (run --sync)`);
}

// ---------- spec coverage ----------
const capabilities = [];
for (const c of CHANGES) {
  const dir = join(ROOT, 'openspec', 'changes', c, 'specs');
  if (!existsSync(dir)) { err(`change ${c}: specs dir missing`); continue; }
  for (const cap of readdirSync(dir)) capabilities.push({ change: c, cap });
}
const allWs = Object.values(ws).map((w) => w.text).join('\n');
for (const { change, cap } of capabilities) {
  if (!new RegExp('[`/]' + cap + '`').test(allWs)) err(`spec coverage: capability "${cap}" (${change}) is not referenced by any workstream`);
}
const capNames = new Set(capabilities.map((c) => c.cap));
for (const [L, w] of Object.entries(ws)) {
  const m = w.text.match(/\*\*Specs:\*\*([^\n]+)/);
  if (!m) { err(`${L}: missing **Specs:** line`); continue; }
  if (L === 'Z') continue;
  const refs = [...m[1].matchAll(/`([a-z0-9-]+)`/g)].map((x) => x[1]).filter((x) => x.includes('-'));
  for (const r of refs) if (!capNames.has(r) && !/^(bootstrap|malva|grocery)-/.test(r) && !['home-landing-page','account-sign-in','password-reset','email-verification','authentication-and-identity','address-book','saved-lists','search-results-page','checkout-page','checkout','order-confirmation-page','delivery-slot-booking','out-of-stock-substitutions','subscriptions-and-recurring-orders','about-us','faq','policy-pages','contact-us','blog-resources','error-pages'].includes(r)) warns.push(`${L}: Specs line references "${r}" which is not a capability or known behavioral spec`);
}

// ---------- scenario counts (informational) ----------
let scenarios = 0;
for (const { change, cap } of capabilities) scenarios += (read(join(ROOT, 'openspec', 'changes', change, 'specs', cap, 'spec.md')).match(/^#### Scenario:/gm) ?? []).length;

// ---------- openspec validate ----------
const cli = spawnSync('openspec', ['--version'], { encoding: 'utf8' });
if (cli.status === 0) {
  for (const c of CHANGES) {
    const r = spawnSync('openspec', ['validate', c, '--strict'], { encoding: 'utf8', cwd: ROOT });
    if (r.status !== 0) err(`openspec validate ${c} failed:\n${r.stdout}${r.stderr}`);
  }
} else warns.push('openspec CLI not found: skipped validation');

// ---------- report ----------
const totalTasks = Object.values(ws).reduce((n, w) => n + w.tasks.length, 0);
console.log(`workstreams: ${Object.keys(ws).length} · tasks: ${totalTasks} · manual tests: ${manual.length} · capabilities: ${capabilities.length} · scenarios: ${scenarios}`);
for (const w of warns) console.log(`warn: ${w}`);
if (errors.length) {
  console.error(`\n${errors.length} error(s):`);
  for (const e of errors) console.error(` - ${e}`);
  process.exit(1);
}
console.log('plan verification: OK');
