import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

export interface ImageEntry { url: string; dimensions: { w: number; h: number } }

export const PRODUCT_IMAGES_FILE = path.join(__dirname, 'product-images.json');
export const SITE_IMAGES_FILE = path.join(__dirname, 'site-images.json');

/** Product key to images, generated by update-images.ts (`{}` until it has run live). */
export function loadProductImages(file = PRODUCT_IMAGES_FILE): Record<string, ImageEntry[]> {
  return existsSync(file) ? (JSON.parse(readFileSync(file, 'utf8')) as Record<string, ImageEntry[]>) : {};
}
